import { Component, HostListener } from '@angular/core';
import { SearchService } from 'src/app/services/search.service';
import { UserDataService } from 'src/app/services/user-data.service';

/**
 * Component for the item list view's toolbar.
 * Includes controls for searching and filtering items.
 */
@Component({
  selector: 'app-item-list-toolbar',
  templateUrl: './item-list-toolbar.component.html',
  styleUrls: ['./item-list-toolbar.component.scss'],
})
export class ItemListToolbarComponent {
  /** Whether the menu with filter controls is visible */
  isFilterMenuVisible = false;

  constructor(
    public readonly searchService: SearchService,
    public readonly userDataService: UserDataService
  ) {}

  /**
   * Shows or hides the filter menu.
   * @param event Event generated by click
   */
  toggleFilterMenu(event: MouseEvent) {
    this.isFilterMenuVisible = !this.isFilterMenuVisible;
    // Prevent click from closing menu through HostListener
    event.stopPropagation();
  }

  /**
   * Sort the items by whether they're favorited (first) or not (last).
   */
  sortByFavorited(): void {
    this.userDataService.sortItemsByFavorited();
    this.searchService.update()
  }

  /**
   * Sort the items by title (alphabetically).
   */
  sortByTitle(): void {
    this.userDataService.sortItemsByTitle();
    this.searchService.update();
  }

  /**
   * Sort the items by date (soonest first).
   */
  sortByDate(): void {
    this.userDataService.sortItemsByDate();
    this.searchService.update();
  }

  /**
   * Close the filter menu when the user clicks outside of it.
   */
  @HostListener('document:click', ['$event'])
  closeFilterMenu() {
    this.isFilterMenuVisible = false;
  }
}
